"""รวมคำแปล → th.lang ไฟล์เดียว, คอมไพล์ Java, ทำ jar, ติดตั้งลง %APPDATA%\\Necesse\\mods

py -m tools.build [--no-install]
"""
import json
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

from tools import langfile, store, thaifont
from tools.paths import BUILD, GAME_JAR, GAME_LIB, JDK_BIN, LOCAL_MODS, MOD_DIR

HEADER = "// Thai Language mod — generated by tools/build.py (อย่าแก้ไฟล์นี้ตรง ๆ แก้ใน data/)"


class BuildError(Exception):
    pass


def include(row: dict) -> bool:
    th = row["th"]
    if not th or row["status"] == "todo":
        return False
    return th != row["official"]


def with_english(row: dict) -> str | None:
    """ชื่อไอเทม/มอนสเตอร์ + (ชื่ออังกฤษ) ไว้ค้นในเน็ต — ข้ามชื่อที่มีตัวแปรหรือเป็นอังกฤษอยู่แล้ว"""
    th, en = row["th"], row["en"]
    if not th or row["status"] == "todo" or "<" in en or th == en:
        return None
    return f"{th} ({en})"


def collect(files: list[Path], append_english: set[str] = frozenset()) -> tuple[list[tuple[str, str, str]], list[str]]:
    by_target: dict[str, dict[str, list[tuple[str, str, str]]]] = {}
    for path in files:
        doc = store.load(path)
        rows = []
        for r in doc["entries"]:
            value = with_english(r) if doc["category"] in append_english else None
            if value is not None:
                rows.append((doc["category"], r["key"], value))
            elif include(r):
                rows.append((doc["category"], r["key"], r["th"]))
        if rows:
            by_target.setdefault(store.target_of(path), {}).setdefault(doc["category"], []).extend(rows)
    out: list[tuple[str, str, str]] = []
    mods = sorted(t for t in by_target if t != "game")
    for target in (["game"] if "game" in by_target else []) + mods:
        for category in sorted(by_target[target]):
            out.extend(by_target[target][category])
    return out, mods


def render_modinfo(template: str, cfg: dict, optional_deps: list[str]) -> str:
    return template.format(optional=", ".join(optional_deps), **cfg)


def compile_java(out: Path) -> None:
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)
    sources = [str(p) for p in (MOD_DIR / "src").rglob("*.java")]
    cp = ";".join([str(GAME_JAR), str(GAME_LIB / "*")])
    r = subprocess.run([str(JDK_BIN / "javac.exe"), "--release", "17", "-encoding", "UTF-8",
                        "-cp", cp, "-d", str(out), *sources], capture_output=True, text=True, errors="replace")
    if r.returncode != 0:
        raise BuildError("javac ล้มเหลว:\n" + r.stdout + r.stderr)


def make_jar(jar: Path, modinfo: str, lang_text: str, classes: Path, font: Path | None,
             font_scale: float = 1.0, font_license: Path | None = None, preview: Path | None = None) -> None:
    jar.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(jar, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("mod.info", modinfo)
        z.writestr("resources/locale/th.lang", lang_text.encode("utf-8"))
        for f in sorted(classes.rglob("*.class")):
            z.write(f, f.relative_to(classes).as_posix())
        if font is not None:
            z.write(font, "thaifont/thai.ttf")
            z.writestr("thaifont/scale.txt", str(font_scale))
        if font_license is not None:
            z.write(font_license, "thaifont/OFL.txt")  # OFL บังคับแนบสัญญาไปกับฟอนต์
        if preview is not None:
            z.write(preview, "resources/preview.png")  # ภาพในเมนู Mods + ภาพหน้า Workshop ตอนอัปโหลด


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    cfg = json.loads((MOD_DIR / "build.json").read_text(encoding="utf-8"))
    rows, mods = collect(store.data_files(), set(cfg.get("appendEnglish", [])))
    lang_text = langfile.dump(rows, header=HEADER)
    BUILD.mkdir(exist_ok=True)
    (BUILD / "th.lang").write_text(lang_text, encoding="utf-8")
    compile_java(BUILD / "classes")
    template = (MOD_DIR / "mod.info.template").read_text(encoding="utf-8")
    info_cfg = {k: cfg[k] for k in ("modid", "name", "version", "gameVersion", "author", "description")}
    modinfo = render_modinfo(template, info_cfg, mods)
    font = None
    if cfg.get("font"):
        font = BUILD / "thai.ttf"
        thaifont.make(MOD_DIR / "fonts" / cfg["font"], font, cfg.get("highCap"))
    jar = BUILD / f"{cfg['jarName']}-{cfg['gameVersion']}-{cfg['version']}.jar"
    scale = float(cfg.get("fontScale", 1.0))
    lic = None
    if cfg.get("font"):
        lic = MOD_DIR / "fonts" / f"OFL-{cfg['font'].split('-')[0]}.txt"
        if not lic.exists():
            raise BuildError(f"ไม่พบไฟล์สัญญาอนุญาตฟอนต์ {lic} (OFL บังคับแนบ)")
    preview = MOD_DIR / "preview.png"
    make_jar(jar, modinfo, lang_text, BUILD / "classes", font, scale, lic, preview if preview.exists() else None)
    print(f"สร้าง {jar.name}: {len(rows)} แถว · มอดที่แปล: {', '.join(mods) or '-'} · ฟอนต์: {cfg.get('font') or '-'} ×{scale}")
    # โฟลเดอร์สำหรับอัปโหลด: เกมอัปโหลดได้เฉพาะ dev mod = โฟลเดอร์ที่มี jar ไฟล์เดียว (เปิดเกมด้วย -mod <โฟลเดอร์>)
    upload = BUILD / "workshop"
    if upload.exists():
        shutil.rmtree(upload)
    upload.mkdir()
    shutil.copy2(jar, upload / jar.name)
    if "--no-install" not in sys.argv:
        LOCAL_MODS.mkdir(parents=True, exist_ok=True)
        for old in LOCAL_MODS.glob(f"{cfg['jarName']}-*.jar"):
            old.unlink()
        shutil.copy2(jar, LOCAL_MODS / jar.name)
        print(f"ติดตั้งแล้ว → {LOCAL_MODS / jar.name}")


if __name__ == "__main__":
    main()
